USE [master]
GO
/****** Object:  Database [JAVALAB]    Script Date: 1/14/2017 1:57:34 PM ******/
CREATE DATABASE [JAVALAB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JAVALAB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\JAVALAB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'JAVALAB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\JAVALAB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [JAVALAB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JAVALAB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JAVALAB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JAVALAB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JAVALAB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JAVALAB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JAVALAB] SET ARITHABORT OFF 
GO
ALTER DATABASE [JAVALAB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JAVALAB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JAVALAB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JAVALAB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JAVALAB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JAVALAB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JAVALAB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JAVALAB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JAVALAB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JAVALAB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [JAVALAB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JAVALAB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JAVALAB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JAVALAB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JAVALAB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JAVALAB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JAVALAB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JAVALAB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JAVALAB] SET  MULTI_USER 
GO
ALTER DATABASE [JAVALAB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JAVALAB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JAVALAB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JAVALAB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [JAVALAB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [JAVALAB]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 1/14/2017 1:57:35 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Code] [nchar](5) NOT NULL,
	[Name] [nchar](50) NOT NULL,
	[Description] [nchar](255) NULL,
	[Price] [float] NOT NULL,
	[Category] [nchar](25) NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [JAVALAB] SET  READ_WRITE 
GO
